#!/usr/bin/env bash

cmd="./lox"

for file in "$1"/*; do
    if [ -f "$file" ]; then
        $cmd "$file" 2>/dev/null

        if [ $? -eq 0 ]; then
            echo -e "\033[32mOK\033[0m   | $(basename $file)"

        else
            echo -e "\033[31mFAIL\033[0m | $(basename $file)"
        fi
    fi
done
