#!/usr/bin/env bash

dst="./lox"
src=$(fd . -e c -tf -d 1)" "$(fd . lib -e c -tf -d 1)
flags="-std=c99 -Wall"

cmd="clang -o $dst $src $flags"

if $cmd; then
    if [ "$1" == "-r" ]; then
        $dst
    fi
fi
